# Generated by Django 3.0.8 on 2020-07-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200712_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('flickr', 'fa-flickr'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('instagram', 'fa-instagram'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
