# Generated by Django 3.0.8 on 2020-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200714_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
