# Generated by Django 3.0.8 on 2020-07-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200715_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g')], max_length=20, null=True),
        ),
    ]
