# Generated by Django 3.0.8 on 2020-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200716_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('pinterest', 'fa-pinterest'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
