# Generated by Django 3.0.8 on 2020-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200716_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('flickr', 'fa-flickr'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
