# Generated by Django 3.0.8 on 2020-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200716_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
