# Generated by Django 3.0.8 on 2020-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200717_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
