# Generated by Django 3.0.8 on 2020-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200717_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('rss', 'fa-rss'), ('flickr', 'fa-flickr'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
