# Generated by Django 3.0.8 on 2020-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20200717_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('pinterest', 'fa-pinterest'), ('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g')], max_length=20, null=True),
        ),
    ]
