# Generated by Django 3.0.8 on 2020-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20200717_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'fa-linkedin-in'), ('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
