# Generated by Django 3.0.8 on 2020-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20200717_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
