# Generated by Django 3.0.8 on 2020-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20200718_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
