# Generated by Django 3.0.8 on 2020-07-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20200718_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('pinterest', 'fa-pinterest'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
