# Generated by Django 3.0.8 on 2020-07-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20200719_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('facebook', 'fa-facebook'), ('flickr', 'fa-flickr')], max_length=20, null=True),
        ),
    ]
