# Generated by Django 3.2 on 2022-07-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0002_auto_20220730_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='proposition.proposition'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='proposition.proposition'),
        ),
    ]
