# Generated by Django 3.0.8 on 2020-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in'), ('rss', 'fa-rss'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
