# Generated by Django 3.0.8 on 2020-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200712_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('dribble', 'fa-dribbble'), ('facebook', 'fa-facebook'), ('instagram', 'fa-instagram'), ('linkedin', 'fa-linkedin-in'), ('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr')], max_length=20, null=True),
        ),
    ]
