# Generated by Django 3.0.8 on 2020-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200712_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('flickr', 'fa-flickr')], max_length=20, null=True),
        ),
    ]
