# Generated by Django 3.0.8 on 2020-07-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200712_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('flickr', 'fa-flickr'), ('google-plus', 'fa-google-plus-g'), ('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('pinterest', 'fa-pinterest'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
