# Generated by Django 3.0.8 on 2020-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200712_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
