# Generated by Django 3.0.8 on 2020-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200714_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook')], max_length=20, null=True),
        ),
    ]
