# Generated by Django 3.0.8 on 2020-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200715_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('facebook', 'fa-facebook')], max_length=20, null=True),
        ),
    ]
