# Generated by Django 3.0.8 on 2020-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200716_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('facebook', 'fa-facebook')], max_length=20, null=True),
        ),
    ]
