# Generated by Django 3.0.8 on 2020-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200716_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr')], max_length=20, null=True),
        ),
    ]
