# Generated by Django 3.0.8 on 2020-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200716_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram'), ('facebook', 'fa-facebook'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
