# Generated by Django 3.0.8 on 2020-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20200717_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
