# Generated by Django 3.0.8 on 2020-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200717_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('flickr', 'fa-flickr'), ('pinterest', 'fa-pinterest'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook')], max_length=20, null=True),
        ),
    ]
