# Generated by Django 3.0.8 on 2020-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200717_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('rss', 'fa-rss'), ('facebook', 'fa-facebook'), ('google-plus', 'fa-google-plus-g'), ('instagram', 'fa-instagram'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble')], max_length=20, null=True),
        ),
    ]
