# Generated by Django 3.0.8 on 2020-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20200717_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
