# Generated by Django 3.0.8 on 2020-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20200719_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
