# Generated by Django 3.0.8 on 2020-07-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20200719_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
