# Generated by Django 3.2 on 2022-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_alter_socialaccount_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook')], max_length=20, null=True),
        ),
    ]
