# Generated by Django 3.2 on 2022-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_alter_socialaccount_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('dribble', 'fa-dribbble'), ('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('pinterest', 'fa-pinterest'), ('flickr', 'fa-flickr')], max_length=20, null=True),
        ),
    ]
