# Generated by Django 3.0.8 on 2020-07-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200716_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/auteur-icon'),
        ),
    ]
