# Generated by Django 3.0.8 on 2020-07-18 23:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200717_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
