# Generated by Django 3.0.8 on 2020-07-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200719_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image3',
        ),
    ]
