# Generated by Django 3.0.8 on 2020-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200712_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auteur',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/single_example'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/single_example2'),
        ),
    ]
