# Generated by Django 3.0.8 on 2020-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200715_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='profile_pic',
            field=models.ImageField(default='/static/images/usericon.png', null=True, upload_to='images/auteur-icon'),
        ),
    ]
