# Generated by Django 3.0.8 on 2020-07-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auteur_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='profile_pic',
            field=models.ImageField(default='../static/images/usericon.png', null=True, upload_to='images/auteur-icon'),
        ),
    ]
