# Generated by Django 3.0.8 on 2020-07-19 00:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
