# Generated by Django 3.0.8 on 2020-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200717_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/users-icon/capture.png', upload_to='images'),
        ),
    ]
